#  base image for Go
FROM golang:latest


# Set the Current Working Directory inside the container
WORKDIR /C:/test/y2_devops_test/main.go


# Build the Go app
RUN go run main.go


# Command to run the executable
CMD ["./main","This mission is finished"]