#  base image for Go
FROM golang:latest


# Set the Current Working Directory inside the container
WORKDIR /C:/test/y2_devops_test/main.go


# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN go build -o main .


# Command to run the executable
CMD ["./main","This mission is finished"]