#  base image for Go
FROM golang:latest


# Set the Current Working Directory inside the container
#WORKDIR /C:/test/y2_devops_test
#WORKDIR C:\test\y2_devops_test

# Build the Go app
RUN go get github.com/gorilla/mux

#COPY / ./

# Command to run the executable
#CMD ["./main","This mission is finished"]
CMD ["go", "run", "main.go"]